# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Flickr-License
version:      0.01
version_from: lib/Flickr/License.pm
installdirs:  site
requires:
    Class::Singleton:              1.03
    Flickr::API:                   0.08
    Flickr::API::Utils:            0.01

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
